// Art Nouveau UI kit cut-outs (generated by scripts/extract-ui-kit.sh).
const assets = import.meta.glob('../../assets/nouveau/*.webp', { eager: true, import: 'default' }) as Record<string, string>;

export function nv(name: string): string {
  return assets[`../../assets/nouveau/${name}.webp`] ?? '';
}
